/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    uint32_t *pclock = (uint32_t *)0x40023830;
    uint32_t *pGPIODMode = (uint32_t *)0x40020C00;
    uint32_t *pSet = (uint32_t *)0x40020C14;

    *pclock |= (1 << 3);

    while(1){

    	for(uint32_t i = 24, j=12; i <= 30; i += 2, j++){
    		*pGPIODMode &= ~(3 << i);

    		*pGPIODMode |= (1 << i);

    		*pSet |= (1 << j);

    		for(int k = 0; k < 100000; k++);

    		*pSet &= ~(1 << j);

    		for(int k = 0; k < 100000; k++);


    	}


   }

}
